Vagrant.configure("2") do |config|
#UBUNTU MACHINE ->

  config.vm.define "projetinho-machine" do |projetinho|
    projetinho.vm.box = "ubuntu/trusty64"
    projetinho.vm.network "public_network", ip: "192.168.0.160", bridge: "Intel(R) Ethernet Connection (7) I219-V"
    projetinho.vm.provider "virtualbox" do |vb|
      vb.name = "projetinho-machine"
    end
  end
end
